@StudentsApi_HostAddress = https://localhost:7281

### Отримати всіх студентів
GET {{StudentsApi_HostAddress}}/api/students

### Отримати студента за Id
GET {{StudentsApi_HostAddress}}/api/students/1

### Створити студента
POST {{StudentsApi_HostAddress}}/api/students
Content-Type: application/json

{ 
  "name": "Test", 
  "grade": 90, 
  "city": "Lviv" 
}

### Оновити студента
PUT {{StudentsApi_HostAddress}}/api/students/999
Content-Type: application/json

{
  "name": "Ghost", 
  "grade": 50, 
  "city": "X"
}

### Видалити студента (існуючий)
DELETE {{StudentsApi_HostAddress}}/api/students/3

### Видалити неіснуючого
DELETE {{StudentsApi_HostAddress}}/api/students/999 