@StudentsApi_HostAddress = https://localhost:7281

### Отримати всіх студентів
GET {{StudentsApi_HostAddress}}/api/students
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJyb21hbkB0ZXN0LmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3ODg5MDE5MDAsImlzcyI6IlN0dWRlbnRzQXBpIiwiYXVkIjoiU3R1ZGVudHNBcGkifQ.jr5NYsjzi1q6KRCFemsrTtabLcRSJUQmDtW_uE_sIRY

### Отримати студента за Id
GET {{StudentsApi_HostAddress}}/api/students/1

### Створити студента
POST {{StudentsApi_HostAddress}}/api/students
Content-Type: application/json

{ 
  "name": "Test", 
  "grade": 90, 
  "city": "Lviv" 
}

### Оновити студента
PUT {{StudentsApi_HostAddress}}/api/students/999
Content-Type: application/json

{
  "name": "Ghost", 
  "grade": 50, 
  "city": "X"
}

### Видалити студента (існуючий)
DELETE {{StudentsApi_HostAddress}}/api/students/3

### Видалити неіснуючого
DELETE {{StudentsApi_HostAddress}}/api/students/999 

### Отримати всі курси
GET {{StudentsApi_HostAddress}}/api/courses

### Створити курс
POST {{StudentsApi_HostAddress}}/api/courses
Content-Type: application/json

{ "title": "A", "credits": 5 }

### Оновити курс
PUT {{StudentsApi_HostAddress}}/api/courses/2
Content-Type:application/json

{ 
  "title": "Biology", 
  "credits": 6 
}

###
GET {{StudentsApi_HostAddress}}/api/courses/999

###
DELETE {{StudentsApi_HostAddress}}/api/courses/1

### Записати студента на курс
POST {{StudentsApi_HostAddress}}/api/enrollments
Content-Type: application/json

{ "studentId": 1, "courseId": 2 }

###
GET {{StudentsApi_HostAddress}}/api/enrollments/student/1

###
POST {{StudentsApi_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "roman@test.com",
  "password": "qwerty123"
}

###
POST {{StudentsApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "roman@test.com",
  "password": "qwerty123"
}
